export const EVALUATION_DIMENSIONS = [
  {
    name: "starting_the_discussion",
    displayName: "Starting the Discussion & Framing",
    description: "Ability to take initiative, set clear definitions, outline the scope, and invite team perspectives early.",
    anchor1: "Did not participate in opening, remained passive until prompted.",
    anchor3: "Contributed early with an initial reaction or basic opinion.",
    anchor5: "Defined clear structural framework, stated nuanced thesis, and invited panel.",
  },
  {
    name: "quality_of_ideas",
    displayName: "Depth & Quality of Ideas",
    description: "Substance of arguments, logical reasoning, factual grounding, and avoiding superficial cliches.",
    anchor1: "Vague, repetitive statements lacking concrete reasoning.",
    anchor3: "Valid arguments with standard reasoning and general knowledge.",
    anchor5: "Multi-dimensional analysis (economic, social, technical) with strong cause-effect logic.",
  },
  {
    name: "building_on_others",
    displayName: "Collaboration & Synthesis",
    description: "Acknowledging other speakers by name, synthesizing conflicting viewpoints, and creating synergy.",
    anchor1: "Spoke in isolation without referencing previous speaker points.",
    anchor3: "Mentioned peers generally or agreed/disagreed without much expansion.",
    anchor5: "Directly cited colleagues by name, connected contrasting arguments, and bridged consensus.",
  },
  {
    name: "listening",
    displayName: "Active Listening & Relevance",
    description: "Staying focused on the conversation flow rather than reciting pre-rehearsed speeches.",
    anchor1: "Derailed discussion to unrelated points or repeated already answered arguments.",
    anchor3: "Addressed the current topic with appropriate context.",
    anchor5: "Reflected nuanced points raised by peers and answered direct questions comprehensively.",
  },
  {
    name: "handling_interruptions",
    displayName: "Composure & Turn Management",
    description: "Gracefully yielding or asserting the floor during cross-talk and interruptions.",
    anchor1: "Talked over others aggressively or completely froze when interrupted.",
    anchor3: "Paused and waited for turn or yielded politely.",
    anchor5: "Firmly and politely held floor when making key point, or gracefully yielded and recaptured turn.",
  },
  {
    name: "ending_strongly",
    displayName: "Concluding & Summarizing",
    description: "Synthesizing the core outcomes and action points concisely in the closing round.",
    anchor1: "Did not offer a summary or merely repeated individual opinion.",
    anchor3: "Gave a decent summary of own points.",
    anchor5: "Balanced synthesis representing all panel viewpoints and concluding with a forward-looking insight.",
  },
] as const;
